#!/usr/bin/env bash
# ai-lint — sweep Rust source for patterns that AI agents commonly leave behind.
#
# Output (one finding per line):
#   text  (default): path:line: rule: message
#   jsonl (--format jsonl): a structured finding object per line —
#     {"tool":"ai-lint","rule":..,"level":"error","path":..,"line":N,
#      "message":..,"fingerprint":"rule:path:line"}
#     stdout stays pure JSONL; human status/summary go to stderr. Exit code is
#     unchanged in both modes.
#
# Rules (intentionally narrow — false positives erode trust fast):
#   stub-macro   todo!() / unimplemented!() / panic!("not implemented"|…)
#   agent-todo   TODO(claude|ai|bot|gpt|assistant|copilot|codex)
#   ai-self-ref  comment references the agent dialog ("as requested", …)
#   diff-relic   // REMOVED: / // PREVIOUSLY: / // WAS: uppercase banners
#
# Overlap with clippy is deliberate and cheap: clippy::todo and
# clippy::unimplemented catch stub-macro too, but only after a full compile in
# the pre-push gate. This runs on staged files in milliseconds with no build.
#
# Rules considered and dropped (so we don't re-introduce them naively):
#   allow-without-reason — clippy::allow_attributes_without_reason owns it
#   missing SAFETY comment — clippy::undocumented_unsafe_blocks owns it
#   unwrap()/expect() — clippy::unwrap_used owns it, with test-scope config a
#     grep cannot replicate
#   lowercase diff relics ("// previously") — legitimate prose trips it
#
# Usage:
#   bash scripts/ai-lint.sh                # scan staged .rs files (pre-commit)
#   bash scripts/ai-lint.sh --all          # scan every tracked .rs file
#   bash scripts/ai-lint.sh --warn-only    # always exit 0, just report
#   bash scripts/ai-lint.sh --format jsonl # emit structured findings (JSONL)
#   bash scripts/ai-lint.sh path/file.rs   # scan explicit files
set -euo pipefail

mode="staged"
warn_only=0
format="text"
explicit=()
while [ $# -gt 0 ]; do
  case "$1" in
    --all) mode="all"; shift ;;
    --warn-only) warn_only=1; shift ;;
    --format) format="${2:-}"; shift 2 ;;
    --format=*) format="${1#*=}"; shift ;;
    -h|--help) sed -n '2,33p' "$0"; exit 0 ;;
    --) shift; explicit+=("$@"); break ;;
    *)  explicit+=("$1"); shift ;;
  esac
done

case "$format" in
  text|jsonl) ;;
  *) echo "ai-lint: unknown --format '$format' (want text|jsonl)" >&2; exit 2 ;;
esac

# In jsonl mode stdout must stay pure JSONL, so human status goes to stderr.
say() { if [ "$format" = "jsonl" ]; then echo "$@" >&2; else echo "$@"; fi; }

cd "$(git rev-parse --show-toplevel)"

# --- file list ----------------------------------------------------------------
raw=()
if [ "${#explicit[@]}" -gt 0 ]; then
  raw=("${explicit[@]}")
elif [ "$mode" = "all" ]; then
  while IFS= read -r f; do raw+=("$f"); done < <(git ls-files -- '*.rs')
else
  while IFS= read -r f; do
    [ -f "$f" ] || continue
    raw+=("$f")
  done < <(git diff --cached --name-only --diff-filter=ACMR -- '*.rs')
fi

files=()
for f in "${raw[@]+"${raw[@]}"}"; do
  case "$f" in
    target/*|*/target/*|vendor/*|*/vendor/*|*.pb.rs|*_generated.rs) continue ;;
  esac
  # prost/tonic and most codegen stamp one of these in the first few lines.
  if [ -f "$f" ] && head -5 "$f" 2>/dev/null | grep -qE '^(//|//!) *(@generated|Code generated|Generated by)'; then
    continue
  fi
  [ -f "$f" ] && files+=("$f")
done

if [ "${#files[@]}" -eq 0 ]; then
  say "  ai-lint: no Rust files to scan."
  exit 0
fi

# --- rules --------------------------------------------------------------------
findings=0

# json_str — JSON-escaped double-quoted string. Only the two bytes that can
# appear in a path or message and break JSON are in play; keep it boring.
json_str() {
  local s="$1"
  s="${s//\\/\\\\}"   # \ -> \\   (must run first)
  s="${s//\"/\\\"}"   # " -> \"
  printf '"%s"' "$s"
}

emit() {  # path lineno rule message  (all rules here are gate-failing)
  if [ "$format" = "jsonl" ]; then
    printf '{"tool":"ai-lint","rule":%s,"level":"error","path":%s,"line":%s,"message":%s,"fingerprint":%s}\n' \
      "$(json_str "$3")" "$(json_str "$1")" "$2" "$(json_str "$4")" "$(json_str "$3:$1:$2")"
  else
    printf '%s:%s: %s: %s\n' "$1" "$2" "$3" "$4"
  fi
  findings=$((findings + 1))
}

# run_rule <name> <egrep-pattern> <message> [scope: all|non-test]
# non-test skips tests/, benches/ and examples/ trees. Inline `#[cfg(test)]`
# modules are not detectable by grep — clippy owns that boundary.
run_rule() {
  local name="$1" pattern="$2" message="$3" scope="${4:-all}" f match loc rest lineno
  for f in "${files[@]}"; do
    if [ "$scope" = "non-test" ]; then
      case "$f" in tests/*|*/tests/*|benches/*|*/benches/*|examples/*|*/examples/*) continue ;; esac
    fi
    while IFS= read -r match; do
      [ -z "$match" ] && continue
      loc="${match%%:*}"
      rest="${match#*:}"
      lineno="${rest%%:*}"
      emit "$loc" "$lineno" "$name" "$message"
    done < <(grep -nHE "$pattern" "$f" 2>/dev/null || true)
  done
}

run_rule stub-macro \
  '(^|[^[:alnum:]_])(todo!|unimplemented!)|panic!\("(not implemented|unimplemented|TODO|FIXME|placeholder)' \
  'stub — finish or remove before committing' \
  non-test

run_rule agent-todo \
  '(TODO|FIXME|XXX)\((claude|ai|bot|gpt|assistant|copilot|codex)\b' \
  'agent-tagged TODO — replace with a real owner or open an issue'

run_rule ai-self-ref \
  '//.*\b([Aa]s requested|[Pp]er your request|[Aa]s you (asked|requested|wanted)|[Ii]n response to your request)\b' \
  'AI prompt artifact — comment references the agent dialog'

run_rule diff-relic \
  '//[[:space:]]*(REMOVED|PREVIOUSLY|WAS):[[:space:]]' \
  'diff relic — uppercase removal banner belongs in commit history, not source'

# --- report -------------------------------------------------------------------
if [ "$findings" -eq 0 ]; then
  say "  ✓ ai-lint: no AI-smell findings in ${#files[@]} file(s)."
  exit 0
fi

say ""
say "  ai-lint: $findings finding(s) in ${#files[@]} file(s)."
[ "$warn_only" -eq 1 ] && exit 0
exit 1
