#!/usr/bin/env bash
# lib.sh — the checks cargo does not already do, defined once.
#
# Each check writes neutral records to stdout, one per line:
#
#     rule<TAB>level<TAB>path<TAB>line<TAB>message
#
# gate.sh renders them for humans, findings.sh renders them as JSONL. Nothing
# in here knows about either format — that is the whole point. Define a check
# once, render it twice.
#
# Sourced, never executed directly.

# ── ai_lint <file...> ────────────────────────────────────────────────────────
# Residue that a compiler cannot see. Deliberately three rules, not four:
# clippy::todo, clippy::unimplemented and clippy::unreachable already cover stub
# macros (verified on a probe crate), so a stub-macro rule here would just
# double-report.
#
# Every rule pipeline ends in `|| true`, and that is load-bearing: grep exits 1
# when a rule does not match, which is the normal case. Callers run this under
# `set -euo pipefail` inside a process substitution, so an unguarded non-match
# would kill the subshell and silently skip every later rule and every later
# file. Same for god_files and dup_deps below — `grep` there exits 1 on the
# healthy case, a workspace with no duplicate versions.
ai_lint() {
  local f
  for f in "$@"; do
    case "$f" in
      target/*|*/target/*|*.pb.rs|*_generated.rs) continue ;;
    esac
    [ -f "$f" ] || continue
    head -5 "$f" 2>/dev/null | grep -qE '^(//|//!) *(@generated|Code generated|Generated by)' && continue

    grep -nHE '(TODO|FIXME|XXX)\((claude|ai|bot|gpt|assistant|copilot|codex)\b' "$f" 2>/dev/null \
      | _rec agent-todo error 'agent-tagged TODO — give it a real owner or open an issue' || true
    grep -nHE '//.*\b([Aa]s requested|[Pp]er your request|[Aa]s you (asked|requested|wanted)|[Ii]n response to your request)\b' "$f" 2>/dev/null \
      | _rec ai-self-ref error 'prompt artifact — the comment is talking to the agent' || true
    grep -nHE '//[[:space:]]*(REMOVED|PREVIOUSLY|WAS):[[:space:]]' "$f" 2>/dev/null \
      | _rec diff-relic error 'diff relic — belongs in commit history, not source' || true
  done
}

# _rec <rule> <level> <message>  — turn `path:line:text` on stdin into records.
_rec() {
  local rule="$1" level="$2" msg="$3" line path lineno
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    path="${line%%:*}"; lineno="${line#*:}"; lineno="${lineno%%:*}"
    printf '%s\t%s\t%s\t%s\t%s\n' "$rule" "$level" "$path" "$lineno" "$msg"
  done
}

# ── god_files ────────────────────────────────────────────────────────────────
# The one structural cap clippy has no opinion about. Complexity is NOT here:
# clippy::cognitive_complexity plus cognitive-complexity-threshold owns that,
# enforced by the lint gate with no second compile and no extra tool.
god_files() {
  local cap="${CAP_LOC:-500}"
  # `-c core.quotePath=` keeps a non-ASCII path as its own bytes instead of
  # C-quoting it into "cr\303\251ate.rs", which names no file on disk.
  #
  # awk takes the path as everything after the count, not as $2: `wc -l` pads
  # the count and then prints the name verbatim, so a path containing a space
  # reported as $2 is truncated at that space. `xargs` splits a large repo into
  # batches and each batch ends in a `total` line; no `*.rs` path can be the
  # bare word `total`, so dropping it by name is exact.
  git -c core.quotePath= ls-files -- '*.rs' \
    | grep -vE '(^|/)(target|vendor)/|(^|/)(tests|benches|examples)/|\.pb\.rs$|_generated\.rs$' \
    | tr '\n' '\0' | xargs -0 wc -l 2>/dev/null \
    | awk -v cap="$cap" '{
        path = $0; sub(/^[[:space:]]*[0-9]+[[:space:]]+/, "", path)
        if ($1 > cap && path != "total")
          printf "god-file\twarning\t%s\t1\t%d LOC over the %d cap\n", path, $1, cap }' \
    || true
}

# ── dup_deps ─────────────────────────────────────────────────────────────────
# Two versions of a crate means two copies in the binary, two build scripts
# running, and a type mismatch the moment either appears in a public signature.
# Offline — the lockfile is the source of truth and a gate must not reach the
# network.
dup_deps() {
  command -v cargo >/dev/null 2>&1 || return 0
  [ -f Cargo.lock ] || return 0
  cargo tree --workspace --duplicates --edges normal --offline 2>/dev/null \
    | grep -E '^[a-zA-Z0-9_.-]+ v[0-9]' | awk '{print $1}' | sort -u \
    | awk '{ printf "duplicate-dep\twarning\tCargo.lock\t1\t%s resolves to more than one version\n", $1 }' \
    || true
}

# ── staged_rs / tracked_rs ───────────────────────────────────────────────────
staged_rs()  { git diff --cached --name-only --diff-filter=ACMR -- '*.rs' 2>/dev/null; }
tracked_rs() { git ls-files -- '*.rs' 2>/dev/null; }

# ── py_toml ──────────────────────────────────────────────────────────────────
# Print the first python on this box that can actually parse TOML, or fail.
#
# A bare `python3` is a PATH lookup, and on macOS that lookup is rigged against
# us: `tomllib` is stdlib only from 3.11, /usr/bin/python3 is 3.9, and
# /usr/libexec/path_helper — run from /etc/zprofile on every login shell —
# rebuilds PATH with /etc/paths ahead of everything, so /usr/bin always
# outranks Homebrew no matter what order was inherited. Seed it with
# `/opt/homebrew/bin:/usr/bin` and it hands back /usr/bin first. The result was
# a gate that failed on the one interpreter in the fleet that cannot do the
# job, on a machine with 3.14 installed two directories away, and said so only
# by ModuleNotFoundError traceback.
#
# So: probe by capability, never by name. `python3` is tried first so a box
# that has already put the right one on PATH — Arch, Ubuntu 24.04 — pays
# nothing and the fleet stays uniform. `tomli` is the pre-3.11 backport and is
# accepted; the callers import it under the same name.
#
# The absolute candidates at the tail are for a PATH stripped down past the
# point where any of the names resolve -- a systemd unit, a launchd job, a
# container with the bare defaults. They cost one failed stat each on a box
# that never needs them.
py_toml() {
  local c
  for c in "${RQ_PYTHON:-}" python3 python3.14 python3.13 python3.12 python3.11 python \
           /opt/homebrew/bin/python3 /usr/local/bin/python3 \
           /home/linuxbrew/.linuxbrew/bin/python3; do
    [ -n "$c" ] || continue
    command -v "$c" >/dev/null 2>&1 || continue
    if "$c" -c 'import tomllib' >/dev/null 2>&1 \
    || "$c" -c 'import tomli'   >/dev/null 2>&1; then
      printf '%s\n' "$c"
      return 0
    fi
  done
  return 1
}
